import { AlertTriangle, Check, Gauge, ListTree, MessageSquareText, Send } from "lucide-react";
import { useState } from "react";
import type { ChapterCandidate, ChapterEvaluation, ChapterVersion, ConsistencyIssue, ConflictExplanation, Draft, EvaluationComparison, QualityGateReport, ReviewSubmission, CanonOperation } from "../types";
import { ChapterCandidatesPanel } from "./ChapterCandidatesPanel";
import { ChapterEvaluationPanel } from "./ChapterEvaluationPanel";
import { VersionHistory } from "./VersionHistory";

interface Props { draft: Draft; issues: ConsistencyIssue[]; conflicts?: ConflictExplanation[]; qualityReport?: QualityGateReport; persistenceError: string; versions?: ChapterVersion[]; evaluations?: ChapterEvaluation[]; candidates?: ChapterCandidate[]; disabled: boolean; onSubmit: (review: ReviewSubmission) => Promise<void>; onApplyCanon?: (operation: CanonOperation) => Promise<void>; onGenerateCandidates?: (count: number, instruction: string) => Promise<void>; onCompareVersions?: (fromVersion: number, toVersion: number) => Promise<string>; onEvaluateVersion?: (versionNumber: number, includeJudge: boolean) => Promise<ChapterEvaluation>; onSetEvaluationBaseline?: (evaluationId: number) => Promise<ChapterEvaluation>; onCompareEvaluations?: (fromVersion: number, toVersion: number) => Promise<EvaluationComparison>; }

export function ReviewPanel({ draft, issues, conflicts = [], qualityReport, persistenceError, versions = [], evaluations = [], candidates = [], disabled, onSubmit, onApplyCanon, onGenerateCandidates, onCompareVersions = async () => "", onEvaluateVersion, onSetEvaluationBaseline, onCompareEvaluations }: Props) {
  const [feedback, setFeedback] = useState("");
  const [sceneNumber, setSceneNumber] = useState<number>();
  const [submitting, setSubmitting] = useState(false);
  const [expandedConflict, setExpandedConflict] = useState<string>();
  const [applyingConflict, setApplyingConflict] = useState<string>();
  async function submit(review: ReviewSubmission) { setSubmitting(true); try { await onSubmit(review); setFeedback(""); setSceneNumber(undefined); } finally { setSubmitting(false); } }
  async function applyRepair(conflict: ConflictExplanation, option: ConflictExplanation["repair_options"][number]) {
    if (option.kind === "canon_operation" && option.operation && onApplyCanon) {
      setApplyingConflict(`${conflict.conflict_id}:${option.id}`);
      try { await onApplyCanon(option.operation); } finally { setApplyingConflict(undefined); }
      return;
    }
    if (option.kind === "revision_feedback" && option.feedback) {
      await submit({ feedback: option.feedback });
    }
  }
  const revisionDisabled = disabled || submitting || !feedback.trim();
  return <aside className="review-panel">
    <div className="review-header"><div className="review-icon"><MessageSquareText size={18} /></div><div><span className="eyebrow">HUMAN REVIEW</span><h2>第 {draft.chapter_number ?? "—"} 章审查</h2></div><span className="review-status">待处理</span></div>
    {persistenceError && <div className="error-callout"><AlertTriangle size={16} /><span>{persistenceError}</span></div>}
    {draft.scene_plan?.length ? <div className="scene-plan-block"><div className="block-label"><ListTree size={14} />修改范围</div><button type="button" className={`scope-option ${sceneNumber === undefined ? "active" : ""}`} aria-pressed={sceneNumber === undefined} onClick={() => setSceneNumber(undefined)} disabled={disabled || submitting}>整章修改</button>{draft.scene_plan.map((scene) => <button type="button" className={`scene-plan-row ${sceneNumber === scene.scene_number ? "active" : ""}`} aria-pressed={sceneNumber === scene.scene_number} onClick={() => setSceneNumber(scene.scene_number)} disabled={disabled || submitting} key={scene.scene_number}><span>{String(scene.scene_number).padStart(2, "0")}</span><div><strong>{scene.goal}</strong><p>{scene.location} · {scene.emotion} · {scene.estimated_words} 字</p></div></button>)}</div> : null}
    {(issues.length > 0 || conflicts.length > 0) && <div className="issue-block"><div className="block-label"><AlertTriangle size={14} />一致性检查</div>{(conflicts.length ? conflicts : issues.map((issue, index) => ({ conflict_id: `legacy-${index}`, type: issue.type ?? "consistency", title: issue.description ?? "一致性问题", severity: issue.severity ?? "low", description: issue.description ?? "未提供描述", evidence: [], conflicting_records: [], impact: "", repair_options: issue.suggestion ? [{ id: "legacy", label: "按建议返修", kind: "revision_feedback", feedback: issue.suggestion }] : [] }))).map((conflict) => <div className="issue" key={conflict.conflict_id}><span className={`severity ${conflict.severity || "low"}`}>{conflict.severity || "low"}</span><div><p>{conflict.description || conflict.title}</p><button type="button" className="issue-detail-toggle" onClick={() => setExpandedConflict((current) => current === conflict.conflict_id ? undefined : conflict.conflict_id)}>{expandedConflict === conflict.conflict_id ? "收起详情" : "查看证据与建议"}</button>{expandedConflict === conflict.conflict_id && <div className="issue-detail"><p className="issue-impact">{conflict.impact}</p>{conflict.evidence.length > 0 && <div className="issue-evidence">{conflict.evidence.map((item, index) => <div key={`${item.label}-${index}`}><strong>{item.label}</strong><span>{typeof item.value === "string" ? item.value : JSON.stringify(item.value)}</span></div>)}</div>}<div className="issue-repair-actions">{conflict.repair_options.map((option) => <button type="button" className="secondary-button" key={option.id} disabled={disabled || submitting || Boolean(applyingConflict)} onClick={() => void applyRepair(conflict, option)}>{applyingConflict === `${conflict.conflict_id}:${option.id}` ? "处理中…" : option.label}</button>)}</div></div>}</div></div>)}</div>}
    {qualityReport && <div className="quality-gate-block"><div className="block-label"><Gauge size={14} />自动质量门</div><div className={`quality-gate-score ${qualityReport.passed ? "passed" : "attention"}`}><strong>{qualityReport.overall_score.toFixed(1)}</strong><span>/ {qualityReport.threshold.toFixed(1)}</span><em>{qualityReport.passed ? "通过" : qualityReport.status === "escalated" ? "转人工" : "待改进"}</em></div>{qualityReport.findings?.filter((item) => item.score < qualityReport.threshold).slice(0, 3).map((item) => <p className="quality-gate-finding" key={item.dimension}><strong>{item.dimension}</strong><span>{item.score.toFixed(1)} 分 · {item.message}</span></p>)}</div>}
    {onGenerateCandidates && <ChapterCandidatesPanel candidates={candidates} currentContent={draft.content ?? ""} disabled={disabled || submitting} onGenerate={onGenerateCandidates} onSelect={(candidateId) => submit({ feedback: "candidate", candidate_id: candidateId })} />}
    <VersionHistory versions={versions} disabled={disabled || submitting} onCompare={onCompareVersions} onRestore={(versionNumber) => submit({ feedback: "restore", version_number: versionNumber })} />
    {onEvaluateVersion && onSetEvaluationBaseline && onCompareEvaluations && <ChapterEvaluationPanel versions={versions} evaluations={evaluations} disabled={disabled || submitting} onEvaluate={onEvaluateVersion} onSetBaseline={onSetEvaluationBaseline} onCompare={onCompareEvaluations} />}
    <div className="review-form"><label htmlFor="feedback">{sceneNumber ? `第 ${sceneNumber} 场修改意见` : "整章修改意见"}</label><textarea id="feedback" value={feedback} onChange={(event) => setFeedback(event.target.value)} placeholder={sceneNumber ? "说明这个场景需要怎样调整……" : "写下整章需要重写的方向……"} disabled={disabled || submitting} rows={7} /><div className="review-actions"><button className="secondary-button" onClick={() => submit({ feedback: feedback.trim(), scene_number: sceneNumber })} disabled={revisionDisabled}><Send size={14} />{sceneNumber ? "重写此场景" : "重写整章"}</button><button className="primary-button" onClick={() => submit({ feedback: "approve" })} disabled={disabled || submitting}><Check size={15} />通过定稿</button></div></div>
  </aside>;
}
